# Generated by Django 4.2.11 on 2024-04-27 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltymodel',
            name='remained',
            field=models.IntegerField(default=0, verbose_name='Остаталось до следущего уровня'),
        ),
        migrations.AddField(
            model_name='loyaltymodel',
            name='total_spent',
            field=models.IntegerField(default=0, verbose_name='Всего потрачено'),
        ),
        migrations.CreateModel(
            name='LoyaltyHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('operation', models.CharField(choices=[('marketing', 'Marketing'), ('bring_in', 'Bring In')], default='marketing', verbose_name='Баланс лояльности')),
                ('value', models.IntegerField(default=0, verbose_name='История')),
                ('total', models.IntegerField(default=0, verbose_name='Итого')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История лояльности',
                'verbose_name_plural': 'История лояльности',
                'db_table': 'profile__loyalty_history',
            },
        ),
    ]
