# Generated by Django 4.2.11 on 2024-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_loyaltymodel_remained_loyaltymodel_total_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltymodel',
            name='remained',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Остаталось до следущего уровня'),
        ),
    ]
