# Generated by Django 4.2.11 on 2024-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_addressmodel_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='code',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Код ПВЗ'),
        ),
    ]
