# Generated by Django 4.2.11 on 2024-05-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_addressmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной адрес'),
        ),
    ]
