services:
  # nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backbone
    depends_on:
      - server
    volumes:
      - media:/media/
      - static:/static/

  # Backend
  server:
    container_name: server
    hostname: server
    restart: always
    build:
      context: ./server
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./server/.env
    networks:
      - backbone
    volumes:
      - media:/app/media/
      - static:/app/static/

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    environment:
      - REDIS_DATABASES=1
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backbone


networks:
  backbone:
    driver: bridge

volumes:
  media:
  static:
