# Generated by Django 4.2.2 on 2023-06-28 16:04

import api.products.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=127, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'product__product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('hex_code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='HEX цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'db_table': 'product__product_color',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=63, verbose_name='МойСклад id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('visible', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
                ('image', models.ImageField(default='product_images/Заглушка фото карточки товара.jpg', max_length=511, upload_to=api.products.models.product_image_upload_path, verbose_name='Выбрать главное изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategorymodel', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product__product',
            },
        ),
        migrations.CreateModel(
            name='ProductSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Название размера')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'db_table': 'product__product_size',
            },
        ),
        migrations.CreateModel(
            name='ProductPathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг (создается автоматически)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productpathmodel', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Путь товара',
                'verbose_name_plural': 'Пути товаров',
                'db_table': 'product__path',
            },
        ),
        migrations.CreateModel(
            name='ProductModificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolormodel', verbose_name='Цвет товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel', verbose_name='Родительский товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsizemodel', verbose_name='Размер товара')),
            ],
            options={
                'verbose_name': 'Модификация товара',
                'verbose_name_plural': 'Модификации товаров',
                'db_table': 'product__product_modification',
            },
        ),
        migrations.CreateModel(
            name='ProductModificationImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product_images/Заглушка фото карточки товара.jpg', max_length=511, upload_to=api.products.models.product_modification_image_upload_path, verbose_name='Выбрать изображение')),
                ('product_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodificationmodel')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'product__modification_image',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpathmodel', verbose_name='Путь к товару'),
        ),
    ]
