# Generated by Django 4.2.2 on 2023-06-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcolormodel_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodificationmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcolormodel', verbose_name='Цвет товара'),
        ),
    ]
