# Generated by Django 4.2.2 on 2023-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodificationmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodificationmodel',
            name='modification_id',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='МойСклад id'),
        ),
    ]
