# Generated by Django 4.2.2 on 2023-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodificationmodel_modification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodificationmodel',
            name='modification_id',
            field=models.CharField(max_length=63, verbose_name='МойСклад id'),
        ),
    ]
