# Generated by Django 4.2.2 on 2023-06-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodificationmodel_modification_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodificationimagemodel',
            table='product__product_modification_image',
        ),
    ]
