# Generated by Django 4.2.2 on 2023-06-28 20:39

import api.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productmodificationimagemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodificationimagemodel',
            name='product_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodificationmodel', verbose_name='Модификация товара'),
        ),
        migrations.CreateModel(
            name='BundleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.CharField(max_length=63, verbose_name='МойСклад id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(default='product_images/Заглушка фото карточки товара.jpg', max_length=511, upload_to=api.products.models.bundle_image_upload_path, verbose_name='Выбрать главное изображение')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpathmodel', verbose_name='Путь к комплекту')),
                ('product_modifications', models.ManyToManyField(blank=True, to='products.productmodificationmodel', verbose_name='Продукты комплекта')),
            ],
            options={
                'verbose_name': 'Комплект товаров',
                'verbose_name_plural': 'Комплекты товаров',
                'db_table': 'product__bundle',
            },
        ),
        migrations.CreateModel(
            name='BundleImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product_images/Заглушка фото карточки товара.jpg', max_length=511, upload_to=api.products.models.bundle_images_upload_path, verbose_name='Выбрать изображение')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.bundlemodel', verbose_name='Комплект')),
            ],
            options={
                'verbose_name': 'Изображение комплекта',
                'verbose_name_plural': 'Изображения комплекторв',
                'db_table': 'product__bundle_image',
            },
        ),
    ]
