# Generated by Django 4.2.2 on 2023-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productmodificationimagemodel_product_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlemodel',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Отображается на сайте?'),
        ),
    ]
