# Generated by Django 4.2.2 on 2023-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_bundlemodel_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
