# Generated by Django 4.2.2 on 2023-06-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_bundlemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategorymodel', verbose_name='Категория товара'),
        ),
    ]
