# Generated by Django 4.2.2 on 2023-07-04 20:05

import api.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bundlemodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundleimagemodel',
            options={'verbose_name': 'Изображение комплекта', 'verbose_name_plural': 'Изображения комплекта'},
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='size_image',
            field=models.ImageField(default='product_images/Заглушка фото карточки товара.jpg', max_length=511, upload_to=api.products.models.category_image_upload_path, verbose_name='Выбрать изображение размеров для категории'),
        ),
    ]
