# Generated by Django 4.2.4 on 2023-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_productmodificationmodel_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="old_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Старая цена"
            ),
        ),
    ]
