# Generated by Django 4.2.4 on 2023-08-19 19:27

import api.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_productmodel_old_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="product_images/Заглушка фото карточки товара.jpg",
                        max_length=511,
                        upload_to=api.products.models.product_color_images_upload_path,
                        verbose_name="Выбрать изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение цвету",
                "verbose_name_plural": "Изображения по цветам",
                "db_table": "product__color_image",
            },
        ),
        migrations.CreateModel(
            name="ProductColorImagesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcolormodel",
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productmodel",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображения товара по цвету",
                "verbose_name_plural": "Изображения товаров по цветам",
                "db_table": "product__product_color_images",
            },
        ),
        migrations.DeleteModel(
            name="ProductModificationImageModel",
        ),
        migrations.AddField(
            model_name="colorimagemodel",
            name="product_color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productcolorimagesmodel",
                verbose_name="Цвет товара",
            ),
        ),
    ]
