# Generated by Django 4.2.4 on 2023-08-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_rename_category_productcategorymodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="code",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Код MoySklad"
            ),
        ),
    ]
