# Generated by Django 4.2.4 on 2023-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_productmodel_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodificationmodel",
            name="visible",
            field=models.BooleanField(
                default=False, verbose_name="Отображается на сайте?"
            ),
        ),
    ]
