# Generated by Django 4.0.6 on 2023-08-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_productmodificationmodel_additional_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundlemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bundlemodel',
            name='path',
        ),
        migrations.RemoveField(
            model_name='bundlemodel',
            name='product_modifications',
        ),
        migrations.DeleteModel(
            name='BundleImageModel',
        ),
        migrations.DeleteModel(
            name='BundleModel',
        ),
    ]
