# Generated by Django 4.2.4 on 2023-10-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_productmodificationmodel_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodificationmodel",
            name="booked",
            field=models.IntegerField(default=0, verbose_name="Забронировано"),
        ),
    ]
