# Generated by Django 4.2.11 on 2024-05-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productmodel_baza_loyalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='baza_loyalty',
        ),
    ]
