# Generated by Django 4.2.11 on 2024-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_productmodel_baza_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='composition_and_care',
            field=models.TextField(default='', verbose_name='Состав и уход'),
        ),
    ]
