# Generated by Django 4.2.11 on 2024-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_reserve_quantity_productmodificationmodel_quantity_reserve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodificationmodel',
            old_name='booked',
            new_name='reserved',
        ),
        migrations.RemoveField(
            model_name='productmodificationmodel',
            name='quantity_reserve',
        ),
        migrations.RemoveField(
            model_name='productmodificationmodel',
            name='quantity_store',
        ),
        migrations.AddField(
            model_name='productmodificationmodel',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
