# Generated by Django 4.2.11 on 2024-05-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_rename_booked_productmodificationmodel_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodificationmodel',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='productmodificationmodel',
            name='reserved',
            field=models.IntegerField(default=0, verbose_name='Забронированый товар'),
        ),
    ]
