# Generated by Django 4.2.11 on 2024-05-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_productmodificationmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='composition_and_care',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Состав и уход'),
        ),
    ]
