# Generated by Django 4.2.4 on 2023-08-19 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0013_productmodel_old_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order2ModificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
            ],
            options={
                "verbose_name": "Заказ к модификации товара",
                "verbose_name_plural": "Заказ к модификациям товаров",
                "db_table": "order__order2modification",
            },
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ("name", models.CharField(max_length=128, verbose_name="Имя клиента")),
                (
                    "surname",
                    models.CharField(max_length=128, verbose_name="Фамилия клиента"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Почта клиента"),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, verbose_name="Телефон клиента"),
                ),
                (
                    "receiving",
                    models.CharField(
                        choices=[("receiving", "Доставка"), ("pickup", "Самовывоз")],
                        max_length=32,
                        verbose_name="Способ получения",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("online", "Картой онлайн"),
                            ("cash", "Наличными"),
                            ("fps", "СБП"),
                        ],
                        max_length=32,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Дом"
                    ),
                ),
                (
                    "frame",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Корпус"
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Квартира"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено?"),
                ),
                (
                    "products_modification",
                    models.ManyToManyField(
                        through="order.Order2ModificationModel",
                        to="products.productmodificationmodel",
                        verbose_name="Модификации продуктов",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "order__order",
            },
        ),
        migrations.AddField(
            model_name="order2modificationmodel",
            name="order_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="order.ordermodel",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="order2modificationmodel",
            name="product_modification_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productmodificationmodel",
                verbose_name="Модификация продукта",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order2modificationmodel",
            unique_together={("order_model", "product_modification_model")},
        ),
    ]
