# Generated by Django 4.2.4 on 2023-08-19 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="number",
            new_name="house",
        ),
    ]
