# Generated by Django 4.2.4 on 2023-08-26 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order2modificationmodel_order_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="products_modification",
            new_name="products",
        ),
    ]
