# Generated by Django 4.0.6 on 2023-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_products_modification_ordermodel_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='receiving',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=32, verbose_name='Способ получения'),
        ),
    ]
