# Generated by Django 4.0.6 on 2023-09-02 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermodel_receiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='baza_loyalty',
            field=models.IntegerField(default=0, verbose_name='Бонусная программа'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='Получен?'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='loaylty_awarded',
            field=models.BooleanField(default=False, verbose_name='Баллы начислены?'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='receiving_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('received', 'Received')], default='created', max_length=32, verbose_name='Статус'),
        ),
    ]
