# Generated by Django 4.0.6 on 2023-09-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermodel_baza_loyalty_ordermodel_is_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2modificationmodel',
            name='baza_loyalty',
            field=models.IntegerField(default=0, verbose_name='Бонусная программа'),
        ),
    ]
