# Generated by Django 4.2.4 on 2023-09-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_productmodificationmodel_weight"),
        ("order", "0008_alter_ordermodel_receiving"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        editable=False, verbose_name="Сумма в копейках"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=250,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Успешно проведен"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=20,
                        verbose_name="Статус транзакции",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=20,
                        verbose_name="Уникальный идентификатор транзакции в системе банка",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=20,
                        verbose_name="Код ошибки",
                    ),
                ),
                (
                    "payment_url",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Ссылка на страницу оплаты. По умолчанию ссылка доступна в течении 24 часов.",
                        max_length=100,
                        verbose_name="Ссылка на страницу оплаты.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Краткое описание ошибки",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Подробное описание ошибки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=64,
                        verbose_name="Электронный адрес для отправки чека покупателю",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Телефон покупателя",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.payment",
                        verbose_name="Платеж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные чека",
                "verbose_name_plural": "Данные чеков",
            },
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Стоимость"),
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена в копейках")),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                ("amount", models.IntegerField(verbose_name="Сумма в копейках")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.productmodificationmodel",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.receipt",
                        verbose_name="Чек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о товаре",
                "verbose_name_plural": "Информация о товарах",
            },
        ),
    ]
