# Generated by Django 4.2.11 on 2024-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_payment_receipt_ordermodel_amount_receiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_fail',
            field=models.BooleanField(default=False, verbose_name='Ошибка платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(editable=False, max_length=100, verbose_name='Номер заказа'),
        ),
    ]
