# Generated by Django 4.2.11 on 2024-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_payment_payment_fail_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='created', max_length=32, verbose_name='Статус'),
        ),
    ]
