# Generated by Django 4.2.11 on 2024-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordermodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2modificationmodel',
            name='baza_loyalty',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='baza_loyalty',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='house',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='street',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='apartment_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='code',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Код ПВЗ'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='floor_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер этажа'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='intercom',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Домофон'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='loyalty_received',
            field=models.IntegerField(default=0, verbose_name='Полученные баллы'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Картой онлайн'), ('cash', 'Наличными'), ('sbp', 'СБП')], max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='receiving',
            field=models.CharField(choices=[('courier', 'Доставка'), ('cdek', 'Пункт СДЕК'), ('pickup', 'Самовывоз')], max_length=32, verbose_name='Способ получения'),
        ),
    ]
