# Generated by Django 4.2.11 on 2024-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_ordermodel_use_loyalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('failed_payment', 'Failed Payment'), ('paid', 'Paid'), ('awaiting_delivery', 'Awaiting Delivery'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='created', max_length=32, verbose_name='Статус'),
        ),
    ]
