# Generated by Django 4.2.11 on 2024-05-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_ordermodel_is_express'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
