# Generated by Django 4.2.11 on 2024-05-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_productmodel_composition_and_care'),
        ('order', '0016_ordermodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productmodificationmodel', verbose_name='Товар'),
        ),
    ]
