# Generated by Django 4.2.11 on 2024-08-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_ordermodel_prepaid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolyamemodel',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма в копейках'),
        ),
        migrations.AlterField(
            model_name='dolyamemodel',
            name='residual_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма подлежащая погашению'),
        ),
    ]
