# Generated by Django 4.2.11 on 2024-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_dolyamemodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolyamemodel',
            name='payment_url',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='Ссылка на страницу оплаты.'),
        ),
    ]
