# Generated by Django 4.2.11 on 2024-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_dolyamemodel_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolyamemodel',
            name='payment_url',
            field=models.CharField(blank=True, default='', editable=False, max_length=500, verbose_name='Ссылка на страницу оплаты.'),
        ),
    ]
