# Generated by Django 4.2.11 on 2024-08-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_dolyamemodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolyamemodel',
            name='commited',
            field=models.BooleanField(default=False, verbose_name='Оплата проведена'),
        ),
    ]
