# Generated by Django 4.2.2 on 2023-06-28 16:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14, verbose_name='Phone')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('lifetime', models.DateTimeField(default=datetime.datetime(2023, 6, 28, 16, 9, 59, 492190, tzinfo=datetime.timezone.utc), verbose_name='Lifetime')),
            ],
            options={
                'verbose_name': 'Код авторизации',
                'verbose_name_plural': 'Коды авторизации',
                'db_table': 'authentication__authcode',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=14, unique=True, verbose_name='Номер телефона')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('is_active', models.BooleanField(default=True, help_text='Пользователь может авторизироваться', verbose_name='Активный')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Администратор')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('basket', models.ManyToManyField(blank=True, to='products.productmodificationmodel', verbose_name='Корзина')),
                ('favorites', models.ManyToManyField(blank=True, to='products.productmodel', verbose_name='Избранное')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'authentication__user',
            },
        ),
    ]
