# Generated by Django 4.2.2 on 2023-07-04 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_authcodemodel_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodemodel',
            name='lifetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 20, 10, 20, 690717, tzinfo=datetime.timezone.utc), verbose_name='Lifetime'),
        ),
    ]
