# Generated by Django 4.2.4 on 2023-08-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_productmodel_old_price"),
        ("authentication", "0014_remove_usermodel_basket_usermodel_apartment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="basket",
            field=models.ManyToManyField(
                blank=True,
                through="authentication.BasketModel",
                to="products.productmodificationmodel",
                verbose_name="Корзина",
            ),
        ),
    ]
