# Generated by Django 4.2.4 on 2023-08-19 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0015_usermodel_basket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="basket",
        ),
    ]
