# Generated by Django 4.2.4 on 2023-08-19 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0016_remove_usermodel_basket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="number",
            new_name="house",
        ),
    ]
