# Generated by Django 4.2.4 on 2023-08-28 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0018_rename_basketmodel_cartmodel_alter_cartmodel_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="favorites",
        ),
    ]
