# Generated by Django 4.2.4 on 2023-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0021_remove_productmodificationmodel_additional_description_and_more",
        ),
        ("authentication", "0019_remove_usermodel_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                to="products.productmodificationmodel",
                verbose_name="Избранное",
            ),
        ),
    ]
