# Generated by Django 4.2.11 on 2024-04-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_usermodel_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='house',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='street',
        ),
    ]
